Commented code of rh-postgresql and devtool for scl_source, it does not work in centos stream 9
Signed-off-by: Mohit Tomar <m.singh19994@gmail.com>

diff --git a/make_rpm b/make_rpm
--- a/make_rpm
+++ b/make_rpm
@@ -123,24 +123,24 @@ if [[ $skip_build == 0 ]]; then
 	sudo ./requirements.sh
 
 	# Enables/verifies the environment for the build
-	source scl_source enable ${rhpg_pkg}
-	status_rh_postgresql=$?
+  # source scl_source enable ${rhpg_pkg}
+	# status_rh_postgresql=$?
 
-	source scl_source enable ${rhgcc_pkg}
-	status_devtoolset=$?
+	# source scl_source enable ${rhgcc_pkg}
+	# status_devtoolset=$?
 
 	command -v pg_isready > /dev/null
 	status_pg_isready=$?
 
-	if [[ $status_rh_postgresql != 0 ]]; then
-		echo "ERROR : it is not possible to enable the ${rhpg_pkg} environment"
-		exit 1
-	fi
+	# if [[ $status_rh_postgresql != 0 ]]; then
+	# 	echo "ERROR : it is not possible to enable the ${rhpg_pkg} environment"
+	# 	exit 1
+	# fi
 
-	if [[ $status_devtoolset != 0 ]]; then
-		echo "ERROR : it is not possible to enable the ${rhgcc_pkg} environment"
-		exit 1
-	fi
+	# if [[ $status_devtoolset != 0 ]]; then
+	# 	echo "ERROR : it is not possible to enable the ${rhgcc_pkg} environment"
+	# 	exit 1
+	# fi
 
 	if [[ $status_pg_isready != 0 ]]; then
 		echo "ERROR : the command pg_isready is not available"
