FOGL-2808: rpm build from source, working stage / initial version

diff --git a/make_rpm b/make_rpm
--- a/make_rpm
+++ b/make_rpm
@@ -21,84 +21,173 @@
 
 set -e
 
-GIT_ROOT=`pwd`    # The script must be executed from the root git directory
+PKG_ROOT=`pwd`               # The script must be executed from the root git directory
+repos="FogLAMP"              # Name of the Git repository
+branch="master"              # Default Git branch to use
+pkg_name="foglamp"           # Name of the package to build
+architecture="x86_64"        # The architecture for which the rpm should be created
+rhpg_pkg="rh-postgresql96"   # Name of the Red Hat package for postgres
+rhgcc_pkg="devtoolset-7"     # Name of the Red Hat package for the newer g++
+skip_build=0                 # 1=skip Git repo extraction and FogLAMP build
 
-pkg_name="foglamp"
-
-
-architecture="none"
-usage="$(basename "$0") help [clean|cleanall]
+usage="$(basename "$0") [-h] [-c] [-a] [-s] [-b <branch>]
 This script is used to create the RPM package of FogLAMP
-Arguments:
- help     - Display this help text
- clean    - Remove all the old versions saved in format .XXXX
- cleanall - Remove all the versions, including the last one"
 
-for i in "$@"
-do
-	case "$i" in
-		clean)
+Arguments:
+ -h	- Display this help text
+ -c	- Remove all the old versions saved in format .XXXX
+ -a	- Remove all the versions, including the last one
+ -s - Skip FogLAMP building using the binaries already available
+ -b	- Branch to base package on"
+
+while getopts ":hcasb:" opt; do
+	case "$opt" in
+		h)
+			echo "${usage}"
+			exit 0
+			;;
+		c)
 			echo -n "Cleaning the build folder from older versions..."
-			find "${GIT_ROOT}/packages/rpmbuild/BUILDROOT" -maxdepth 1 | grep '.*\.[0-9][0-9][0-9][0-9]' | xargs rm -rf
+			find "${PKG_ROOT}/packages/rpmbuild/BUILDROOT" -maxdepth 1 | grep '.*\.[0-9][0-9][0-9][0-9]' | sudo xargs rm -rf
 			echo "Done."
 			exit 0
 			;;
-		cleanall)
-			if [ -d "${GIT_ROOT}/packages/rpmbuild/BUILDROOT" ]; then
+		a)
+			if [ -d "${PKG_ROOT}/packages/rpmbuild/BUILDROOT" ]; then
 
 				echo -n "Cleaning the build folder..."
-				sudo rm -rf ${GIT_ROOT}/packages/rpmbuild/BUILDROOT/*
+				sudo rm -rf ${PKG_ROOT}/packages/rpmbuild/BUILDROOT/*
 				echo "Done."
 			else
 				echo "No build folder, skipping cleanall"
 			fi
 			exit 0
 			;;
-
-		--help)
-			echo "${usage}"
-			exit 0
+		s)
+			skip_build=1
 			;;
-		*)
-		echo "Unrecognized option: $i"
-		exit 1
-		;;
+		b)
+			branch=$OPTARG
+			;;
+		\?)
+			echo "Invalid option -$OPTARG"
+			exit 1
+			;;
+		:)
+			echo "-$OPTARG requires an argument"
+			exit 1
 	esac
 done
 
-architecture="x86_64"
 
 # If the architecture has not been defined, then the script is complete
 if [[ "$architecture" == "none" ]]; then
   exit 0
 fi
 
-# Check FOGLAMP_ROOT
+if [ ! -f packages/rpmbuild/SPECS/foglamp.spec ] ; then
+	echo You must run this script from the foglamp-pkg directory
+	exit 1
+fi
+
+#
+# Extracts/updates Git repository
+#
+if [[ $skip_build == 0 ]]; then
+
+	cd /tmp
+	if [ -d "$repos" ]; then
+		echo WARNING: Repository $repos already exists, using the existing copy
+		(cd $repos; git fetch --all; git pull ; git checkout "$branch")
+	else
+		git clone -b "$branch" https://github.com/foglamp/${repos}.git
+	fi
+
+	GIT_ROOT=/tmp/"$repos"
+	cd ${GIT_ROOT}
+fi
+
+#
+# Builds FogLAMP
+#
+if [[ $skip_build == 0 ]]; then
+
+	# Backups FOGLAMP_ROOT
+	export FOGLAMP_ROOT_BCK=${FOGLAMP_ROOT}
+
+	export FOGLAMP_ROOT=${GIT_ROOT}
+	export FOGLAMP_DATA=${FOGLAMP_ROOT}/data
+	export PYTHONPATH=${FOGLAMP_ROOT}/python
+
+	set +e
+
+	cd ${FOGLAMP_ROOT}
+	sudo ./requirements.sh
+
+	# Enables/verifies the environment for the build
+	source scl_source enable ${rhpg_pkg}
+	status_rh_postgresql96=$?
+
+	source scl_source enable ${rhgcc_pkg}
+	status_devtoolset=$?
+
+	command -v pg_isready > /dev/null
+	status_pg_isready=$?
+
+	if [[ $status_rh_postgresql96 != 0 ]]; then
+
+		echo "ERROR : it is not possible to enable the ${rhpg_pkg} environment"
+		exit 1
+	fi
+
+	if [[ $status_devtoolset != 0 ]]; then
+
+		echo "ERROR : it is not possible to enable the ${rhgcc_pkg} environment"
+		exit 1
+	fi
+
+	if [[ $status_pg_isready != 0 ]]; then
+
+		echo "ERROR : the command pg_isready is not available"
+		exit 1
+	fi
+
+	set -e
+
+	make
+	sudo make install
+
+	# Restores FOGLAMP_ROOT
+	export FOGLAMP_ROOT=${FOGLAMP_ROOT_BCK}
+fi
+
+# Checks if the FOGLAMP_ROOT environment is defined
 if [ -z ${FOGLAMP_ROOT+x} ]; then
+
     # Set FOGLAMP_ROOT as the default directory
-    if [ -d "/usr/local/foglamp" ]; then
-      FOGLAMP_ROOT="/usr/local/foglamp"
-      export FOGLAMP_ROOT
-    else
-      echo "No FOGLAMP_ROOT directory found - Program exit."
-      exit 1
-    fi
+	export FOGLAMP_ROOT="/usr/local/foglamp"
+fi
+
+if [ ! -d "${FOGLAMP_ROOT}" ]; then
+
+  echo "No FOGLAMP_ROOT directory found in the path ${FOGLAMP_ROOT} - Program exit."
+  exit 1
 fi
 
 version=`cat ${FOGLAMP_ROOT}/VERSION | tr -d ' ' | grep 'foglamp_version=' | head -1 | sed -e 's/\(.*\)=\(.*\)/\2/g'`
-BUILD_ROOT="${GIT_ROOT}/packages/rpmbuild/BUILDROOT"
+BUILD_ROOT="${PKG_ROOT}/packages/rpmbuild/BUILDROOT"
 
-mkdir -p ${GIT_ROOT}/packages/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
-mkdir -p ${GIT_ROOT}/packages/rpmbuild/RPMS/x86_64
+mkdir -p ${PKG_ROOT}/packages/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
+mkdir -p ${PKG_ROOT}/packages/rpmbuild/RPMS/x86_64
 
 # Final package name
 package_name="${pkg_name}-${version}-1.${architecture}"
 
 # Print the summary of findings
-echo "The package root directory is : ${GIT_ROOT}"
+echo "The package root directory is : ${PKG_ROOT}"
 echo "The FogLAMP directory is      : ${FOGLAMP_ROOT}"
 echo "The FogLAMP version is        : ${version}"
-echo "The package will be built in  : ${GIT_ROOT}/packages/rpmbuild/RPMS/${architecture}"
+echo "The package will be built in  : ${PKG_ROOT}/packages/rpmbuild/RPMS/${architecture}"
 echo "The package name is           : ${package_name}"
 echo
 
@@ -125,9 +214,9 @@ mkdir "${package_name}"
 echo -n "Populating the package and updating version in control file..."
 cd "${package_name}"
 
-sed -i "s/__NAME__/${pkg_name}/g"     ${GIT_ROOT}/packages/rpmbuild/SPECS/foglamp.spec
-sed -i "s/__VERSION__/${version}/g"   ${GIT_ROOT}/packages/rpmbuild/SPECS/foglamp.spec
-sed -i "s/__ARCH__/${architecture}/g" ${GIT_ROOT}/packages/rpmbuild/SPECS/foglamp.spec
+sed -i "s/__NAME__/${pkg_name}/g"     ${PKG_ROOT}/packages/rpmbuild/SPECS/foglamp.spec
+sed -i "s/__VERSION__/${version}/g"   ${PKG_ROOT}/packages/rpmbuild/SPECS/foglamp.spec
+sed -i "s/__ARCH__/${architecture}/g" ${PKG_ROOT}/packages/rpmbuild/SPECS/foglamp.spec
 
 mkdir -p usr/local/foglamp
 cd usr/local/foglamp
@@ -159,7 +248,7 @@ if [ -e "${package_name}.rpm" ]; then
 fi
 
 echo "Building the new package..."
-base_dir=${GIT_ROOT}/packages
+base_dir=${PKG_ROOT}/packages
 rpmbuild --define "_topdir ${base_dir}/rpmbuild"   --noclean -bb ${base_dir}/rpmbuild/SPECS/foglamp.spec
 echo "Building Complete."
 
