service notification version fixes

diff --git a/plugins/make_deb b/plugins/make_deb
--- a/plugins/make_deb
+++ b/plugins/make_deb
@@ -105,16 +105,16 @@ do
 	pkg_name="${REPO_NAME}"
 
     if [ -f "${GIT_ROOT}/VERSION" ]; then
-		version=`cat "${GIT_ROOT}/VERSION"`
+        version=`cat "${GIT_ROOT}/VERSION"`
         foglamp_version=`cat ${GIT_ROOT}/foglamp.version | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
-	elif [ -f "${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name}" ]; then
-		  version=`cat "${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name}" | tr -d ' ' | grep "foglamp_${plugin_type}_${plugin_name}_version" | head -1 | sed -e 's/\(.*\)=\(.*\)/\2/g'`
-		  foglamp_version=`cat ${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name} | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
-	else
-		echo Unable to determine version of package to create
-		rm -rf "${GIT_ROOT}"
-		exit 1
-	fi
+    elif [ -f "${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name}" ]; then
+        version=`cat "${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name}" | tr -d ' ' | grep "foglamp_${plugin_type}_${plugin_name}_version" | head -1 | sed -e 's/\(.*\)=\(.*\)/\2/g'`
+        foglamp_version=`cat ${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name} | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
+    else
+        echo Unable to determine version of package to create
+        rm -rf "${GIT_ROOT}"
+        exit 1
+    fi
 	echo Version is $version
     BUILD_ROOT="${GIT_ROOT}/packages/build"
     if [ "${plugin_package_name}" ]; then
@@ -131,9 +131,9 @@ do
     echo "The package will be built in                          : ${BUILD_ROOT}"
     echo "The package name is                                   : ${package_name}"
     if [ -f "${GIT_ROOT}/service_notification.version" ]; then
-	     service_notification_version=`cat ${GIT_ROOT}/service_notification.version | tr -d ' ' | grep 'service_notification_version' | head -1 | sed -e 's/\(.*\)version\([>=|>|<|<=|=]*\)\(.*\)/\2 \3/g'`
-	     echo "The Service notification required version        : ${service_notification_version}"
-	fi
+        service_notification_version=`cat ${GIT_ROOT}/service_notification.version | tr -d ' ' | grep 'service_notification_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
+        echo "The Service notification required version        : ${service_notification_version}"
+    fi
     echo
 
     # Create the package directory. If a directory with the same name exists,
@@ -155,20 +155,20 @@ do
     mkdir "${package_name}"
 
     # If plugin_type_install if not set use plugin_type value
-	if [ "${plugin_type}" = "notify" ]; then
-	    plugin_type_install="notificationDelivery"
+    if [ "${plugin_type}" = "notify" ]; then
+        plugin_type_install="notificationDelivery"
     elif [ "${plugin_type}" = "rule" ]; then
-	    plugin_type_install="notificationRule"
-	else
-	    plugin_type_install=${plugin_type}
-	fi
+        plugin_type_install="notificationRule"
+    else
+        plugin_type_install=${plugin_type}
+    fi
 
-	# Install directory path
-	if [ -d ${GIT_ROOT}/python ]; then
-	    installs=python/foglamp/plugins/${plugin_type_install}/${plugin_install_dirname}
-	else
-	    installs=plugins/${plugin_type_install}/${plugin_install_dirname}
-	fi
+    # Install directory path
+    if [ -d ${GIT_ROOT}/python ]; then
+        installs=python/foglamp/plugins/${plugin_type_install}/${plugin_install_dirname}
+    else
+        installs=plugins/${plugin_type_install}/${plugin_install_dirname}
+    fi
 
     # Populate the package directory with Debian files
     # First with files common to all plugins
@@ -179,33 +179,36 @@ do
     deb_path=${BUILD_ROOT}/${package_name}/DEBIAN
     cp -R ${PKG_ROOT}/packages/DEBIAN/* ${deb_path}
     sed -i "s/__VERSION__/${version}/g" ${deb_path}/control
-	sed -i "s/__NAME__/${pkg_name}/g" ${deb_path}/control
-	sed -i "s/__ARCH__/${archname}/g" ${deb_path}/control
-	sed -i "s/__REQUIRES__/${requirements}/g" ${deb_path}/control
-	sed -i "s/foglamp,/foglamp (${foglamp_version}),/" ${deb_path}/control
-	sed -i "s/foglamp$/foglamp (${foglamp_version})/" ${deb_path}/control
-	sed -i "s|__INSTALL_DIR__|${installs}|g" ${deb_path}/postinst
-	sed -i "s/__PLUGIN_NAME__/${plugin_name}/g" ${deb_path}/postinst
+    sed -i "s/__NAME__/${pkg_name}/g" ${deb_path}/control
+    sed -i "s/__ARCH__/${archname}/g" ${deb_path}/control
+    sed -i "s/__REQUIRES__/${requirements}/g" ${deb_path}/control
+    sed -i "s/foglamp,/foglamp (${foglamp_version}),/" ${deb_path}/control
+    sed -i "s/foglamp$/foglamp (${foglamp_version})/" ${deb_path}/control
+    sed -i "s|__INSTALL_DIR__|${installs}|g" ${deb_path}/postinst
+    sed -i "s/__PLUGIN_NAME__/${plugin_name}/g" ${deb_path}/postinst
     desc=`cat "${GIT_ROOT}/Description"`
     sed -i "s/__DESCRIPTION__/${desc}/g" ${deb_path}/control
+    if [ ! -z "${service_notification_version}" ] ; then
+        sed -i "s/foglamp-service-notification/foglamp-service-notification (${service_notification_version})/" ${deb_path}/control
+    fi
 
     # Creating packaging file structure
     mkdir -p usr/local/foglamp
     cd usr/local/foglamp
     if [ -d ${GIT_ROOT}/python ]; then
-		find ${GIT_ROOT}/python | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
-		cp -R ${GIT_ROOT}/python .
-		cp -R ${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name} .
-	else
-		(cd ${GIT_ROOT};
-			if [ -f requirements.sh ]; then
-				./requirements.sh
-			fi
-			mkdir -p build; cd build; cmake ..; make)
-		mkdir -p "plugins/${plugin_type_install}/${plugin_install_dirname}"
-		cp -R --preserve=links ${GIT_ROOT}/build/lib* "plugins/${plugin_type_install}/${plugin_install_dirname}"
-	fi
-	echo "Done."
+        find ${GIT_ROOT}/python | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
+        cp -R ${GIT_ROOT}/python .
+        cp -R ${GIT_ROOT}/VERSION.${plugin_type}.${plugin_name} .
+    else
+        (cd ${GIT_ROOT};
+        if [ -f requirements.sh ]; then
+            ./requirements.sh
+        fi
+        mkdir -p build; cd build; cmake ..; make)
+        mkdir -p "plugins/${plugin_type_install}/${plugin_install_dirname}"
+        cp -R --preserve=links ${GIT_ROOT}/build/lib* "plugins/${plugin_type_install}/${plugin_install_dirname}"
+    fi
+    echo "Done."
 
     # Build the package
     cd "${BUILD_ROOT}"
@@ -226,10 +229,9 @@ do
 
     # Move final package to archive directory
     cp  ${BUILD_ROOT}/${package_name}.deb ${archive}/${arch}/${fullname}
-	cp -R ${BUILD_ROOT}/${package_name} ${archive}/${arch}/${fullname}
+    cp -R ${BUILD_ROOT}/${package_name} ${archive}/${arch}/${fullname}
 
     rm -rf /tmp/${REPO_NAME}
     exit 0
 done
 exit 0
-
